// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift

import UIKit

struct R {
  static func validate() {
    storyboard.login.validateImages()
    storyboard.login.validateViewControllers()
    storyboard.launchScreen.validateImages()
    storyboard.launchScreen.validateViewControllers()
    storyboard.sMS.validateImages()
    storyboard.sMS.validateViewControllers()
    storyboard.main.validateImages()
    storyboard.main.validateViewControllers()
  }
  
  struct file {
    static var cityPlist: NSURL? { return NSBundle.mainBundle().URLForResource("City", withExtension: "plist") }
    static var imgBundle: NSURL? { return NSBundle.mainBundle().URLForResource("img", withExtension: "bundle") }
  }
  
  struct font {
    
  }
  
  struct image {
    static var brandAssets: UIImage? { return UIImage(named: "Brand Assets") }
    static var guidance1: UIImage? { return UIImage(named: "Guidance1") }
    static var guidance2: UIImage? { return UIImage(named: "Guidance2") }
    static var guidance3: UIImage? { return UIImage(named: "Guidance3") }
    static var guidance4: UIImage? { return UIImage(named: "Guidance4") }
    static var mine_photo: UIImage? { return UIImage(named: "mine_photo") }
    static var tata_close: UIImage? { return UIImage(named: "tata_close") }
  }
  
  struct nib {
    static var accountTableViewCell: _R.nib._AccountTableViewCell { return _R.nib._AccountTableViewCell() }
    static var cFCityCell: _R.nib._CFCityCell { return _R.nib._CFCityCell() }
    static var citySearchResultVC: _R.nib._CitySearchResultVC { return _R.nib._CitySearchResultVC() }
    static var clockCollectionHeaderView: _R.nib._ClockCollectionHeaderView { return _R.nib._ClockCollectionHeaderView() }
    static var clockCollectionViewCell: _R.nib._ClockCollectionViewCell { return _R.nib._ClockCollectionViewCell() }
    static var cupHeaderView: _R.nib._CupHeaderView { return _R.nib._CupHeaderView() }
    static var headerItemView: _R.nib._HeaderItemView { return _R.nib._HeaderItemView() }
    static var kSGuidanceViewController: _R.nib._KSGuidanceViewController { return _R.nib._KSGuidanceViewController() }
    static var mineTableViewCell: _R.nib._MineTableViewCell { return _R.nib._MineTableViewCell() }
    static var temperatureTableViewCell: _R.nib._TemperatureTableViewCell { return _R.nib._TemperatureTableViewCell() }
  }
  
  struct reuseIdentifier {
    static var accountTableViewCell: ReuseIdentifier<Cup.AccountTableViewCell> { return ReuseIdentifier(identifier: "AccountTableViewCell") }
    static var clockCollectionHeaderView: ReuseIdentifier<Cup.ClockCollectionHeaderView> { return ReuseIdentifier(identifier: "ClockCollectionHeaderView") }
    static var clockCollectionViewCell: ReuseIdentifier<Cup.ClockCollectionViewCell> { return ReuseIdentifier(identifier: "ClockCollectionViewCell") }
    static var mineTableViewCell: ReuseIdentifier<Cup.MineTableViewCell> { return ReuseIdentifier(identifier: "MineTableViewCell") }
    static var temperatureTableViewCell: ReuseIdentifier<Cup.TemperatureTableViewCell> { return ReuseIdentifier(identifier: "TemperatureTableViewCell") }
  }
  
  struct segue {
    
  }
  
  struct storyboard {
    struct launchScreen {
      static var initialViewController: UIViewController? { return instance.instantiateInitialViewController() }
      static var instance: UIStoryboard { return UIStoryboard(name: "LaunchScreen", bundle: nil) }
      
      static func validateImages() {
        
      }
      
      static func validateViewControllers() {
        
      }
    }
    
    struct login {
      static var initialViewController: UINavigationController? { return instance.instantiateInitialViewController() as? UINavigationController }
      static var instance: UIStoryboard { return UIStoryboard(name: "Login", bundle: nil) }
      static var login: Cup.UserLoginViewController? { return instance.instantiateViewControllerWithIdentifier("login") as? Cup.UserLoginViewController }
      static var register: Cup.UserRegistViewController? { return instance.instantiateViewControllerWithIdentifier("register") as? Cup.UserRegistViewController }
      
      static func validateImages() {
        assert(UIImage(named: "logo") != nil, "[R.swift] Image named 'logo' is used in storyboard 'Login', but couldn't be loaded.")
      }
      
      static func validateViewControllers() {
        assert(login != nil, "[R.swift] ViewController with identifier 'login' could not be loaded from storyboard 'Login' as 'Cup.UserLoginViewController'.")
        assert(register != nil, "[R.swift] ViewController with identifier 'register' could not be loaded from storyboard 'Login' as 'Cup.UserRegistViewController'.")
      }
    }
    
    struct main {
      static var initialViewController: Cup.TabBarViewController? { return instance.instantiateInitialViewController() as? Cup.TabBarViewController }
      static var instance: UIStoryboard { return UIStoryboard(name: "Main", bundle: nil) }
      
      static func validateImages() {
        
      }
      
      static func validateViewControllers() {
        
      }
    }
    
    struct sMS {
      static var initialViewController: UINavigationController? { return instance.instantiateInitialViewController() as? UINavigationController }
      static var instance: UIStoryboard { return UIStoryboard(name: "SMS", bundle: nil) }
      
      static func validateImages() {
        
      }
      
      static func validateViewControllers() {
        
      }
    }
  }
}

struct _R {
  struct nib {
    struct _AccountTableViewCell: NibResource, Reusable {
      var instance: UINib { return UINib.init(nibName: "AccountTableViewCell", bundle: nil) }
      var name: String { return "AccountTableViewCell" }
      var reuseIdentifier: ReuseIdentifier<Cup.AccountTableViewCell> { return ReuseIdentifier(identifier: "AccountTableViewCell") }
      
      func firstView(ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]?) -> Cup.AccountTableViewCell? {
        return instantiateWithOwner(ownerOrNil, options: optionsOrNil)[0] as? Cup.AccountTableViewCell
      }
      
      func instantiateWithOwner(ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]?) -> [AnyObject] {
        return instance.instantiateWithOwner(ownerOrNil, options: optionsOrNil)
      }
    }
    
    struct _CFCityCell: NibResource {
      var instance: UINib { return UINib.init(nibName: "CFCityCell", bundle: nil) }
      var name: String { return "CFCityCell" }
      
      func firstView(ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]?) -> Cup.CFCityCell? {
        return instantiateWithOwner(ownerOrNil, options: optionsOrNil)[0] as? Cup.CFCityCell
      }
      
      func instantiateWithOwner(ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]?) -> [AnyObject] {
        return instance.instantiateWithOwner(ownerOrNil, options: optionsOrNil)
      }
    }
    
    struct _CitySearchResultVC: NibResource {
      var instance: UINib { return UINib.init(nibName: "CitySearchResultVC", bundle: nil) }
      var name: String { return "CitySearchResultVC" }
      
      func firstView(ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]?) -> UIView? {
        return instantiateWithOwner(ownerOrNil, options: optionsOrNil)[0] as? UIView
      }
      
      func instantiateWithOwner(ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]?) -> [AnyObject] {
        return instance.instantiateWithOwner(ownerOrNil, options: optionsOrNil)
      }
    }
    
    struct _ClockCollectionHeaderView: NibResource, Reusable {
      var instance: UINib { return UINib.init(nibName: "ClockCollectionHeaderView", bundle: nil) }
      var name: String { return "ClockCollectionHeaderView" }
      var reuseIdentifier: ReuseIdentifier<Cup.ClockCollectionHeaderView> { return ReuseIdentifier(identifier: "ClockCollectionHeaderView") }
      
      func firstView(ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]?) -> Cup.ClockCollectionHeaderView? {
        return instantiateWithOwner(ownerOrNil, options: optionsOrNil)[0] as? Cup.ClockCollectionHeaderView
      }
      
      func instantiateWithOwner(ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]?) -> [AnyObject] {
        return instance.instantiateWithOwner(ownerOrNil, options: optionsOrNil)
      }
    }
    
    struct _ClockCollectionViewCell: NibResource, Reusable {
      var instance: UINib { return UINib.init(nibName: "ClockCollectionViewCell", bundle: nil) }
      var name: String { return "ClockCollectionViewCell" }
      var reuseIdentifier: ReuseIdentifier<Cup.ClockCollectionViewCell> { return ReuseIdentifier(identifier: "ClockCollectionViewCell") }
      
      func firstView(ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]?) -> Cup.ClockCollectionViewCell? {
        return instantiateWithOwner(ownerOrNil, options: optionsOrNil)[0] as? Cup.ClockCollectionViewCell
      }
      
      func instantiateWithOwner(ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]?) -> [AnyObject] {
        return instance.instantiateWithOwner(ownerOrNil, options: optionsOrNil)
      }
    }
    
    struct _CupHeaderView: NibResource {
      var instance: UINib { return UINib.init(nibName: "CupHeaderView", bundle: nil) }
      var name: String { return "CupHeaderView" }
      
      func firstView(ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]?) -> Cup.CupHeaderView? {
        return instantiateWithOwner(ownerOrNil, options: optionsOrNil)[0] as? Cup.CupHeaderView
      }
      
      func instantiateWithOwner(ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]?) -> [AnyObject] {
        return instance.instantiateWithOwner(ownerOrNil, options: optionsOrNil)
      }
    }
    
    struct _HeaderItemView: NibResource {
      var instance: UINib { return UINib.init(nibName: "HeaderItemView", bundle: nil) }
      var name: String { return "HeaderItemView" }
      
      func firstView(ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]?) -> Cup.HeaderItemView? {
        return instantiateWithOwner(ownerOrNil, options: optionsOrNil)[0] as? Cup.HeaderItemView
      }
      
      func instantiateWithOwner(ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]?) -> [AnyObject] {
        return instance.instantiateWithOwner(ownerOrNil, options: optionsOrNil)
      }
    }
    
    struct _KSGuidanceViewController: NibResource {
      var instance: UINib { return UINib.init(nibName: "KSGuidanceViewController", bundle: nil) }
      var name: String { return "KSGuidanceViewController" }
      
      func firstView(ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]?) -> Cup.KSGuidanceViewController? {
        return instantiateWithOwner(ownerOrNil, options: optionsOrNil)[0] as? Cup.KSGuidanceViewController
      }
      
      func instantiateWithOwner(ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]?) -> [AnyObject] {
        return instance.instantiateWithOwner(ownerOrNil, options: optionsOrNil)
      }
    }
    
    struct _MineTableViewCell: NibResource, Reusable {
      var instance: UINib { return UINib.init(nibName: "MineTableViewCell", bundle: nil) }
      var name: String { return "MineTableViewCell" }
      var reuseIdentifier: ReuseIdentifier<Cup.MineTableViewCell> { return ReuseIdentifier(identifier: "MineTableViewCell") }
      
      func firstView(ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]?) -> Cup.MineTableViewCell? {
        return instantiateWithOwner(ownerOrNil, options: optionsOrNil)[0] as? Cup.MineTableViewCell
      }
      
      func instantiateWithOwner(ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]?) -> [AnyObject] {
        return instance.instantiateWithOwner(ownerOrNil, options: optionsOrNil)
      }
    }
    
    struct _TemperatureTableViewCell: NibResource, Reusable {
      var instance: UINib { return UINib.init(nibName: "TemperatureTableViewCell", bundle: nil) }
      var name: String { return "TemperatureTableViewCell" }
      var reuseIdentifier: ReuseIdentifier<Cup.TemperatureTableViewCell> { return ReuseIdentifier(identifier: "TemperatureTableViewCell") }
      
      func firstView(ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]?) -> Cup.TemperatureTableViewCell? {
        return instantiateWithOwner(ownerOrNil, options: optionsOrNil)[0] as? Cup.TemperatureTableViewCell
      }
      
      func instantiateWithOwner(ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]?) -> [AnyObject] {
        return instance.instantiateWithOwner(ownerOrNil, options: optionsOrNil)
      }
    }
  }
}

struct ReuseIdentifier<T>: CustomStringConvertible {
  let identifier: String
  
  var description: String { return identifier }
}

protocol NibResource {
  var instance: UINib { get }
  var name: String { get }
}

protocol Reusable {
  typealias T
  
  var reuseIdentifier: ReuseIdentifier<T> { get }
}

extension UITableView {
  func dequeueReusableCellWithIdentifier<T : UITableViewCell>(identifier: ReuseIdentifier<T>, forIndexPath indexPath: NSIndexPath?) -> T? {
    if let indexPath = indexPath {
      return dequeueReusableCellWithIdentifier(identifier.identifier, forIndexPath: indexPath) as? T
    }
    return dequeueReusableCellWithIdentifier(identifier.identifier) as? T
  }
  
  func dequeueReusableCellWithIdentifier<T : UITableViewCell>(identifier: ReuseIdentifier<T>) -> T? {
    return dequeueReusableCellWithIdentifier(identifier.identifier) as? T
  }
  
  func dequeueReusableHeaderFooterViewWithIdentifier<T : UITableViewHeaderFooterView>(identifier: ReuseIdentifier<T>) -> T? {
    return dequeueReusableHeaderFooterViewWithIdentifier(identifier.identifier) as? T
  }
  
  func registerNib<T: NibResource where T: Reusable, T.T: UITableViewCell>(nibResource: T) {
    registerNib(nibResource.instance, forCellReuseIdentifier: nibResource.reuseIdentifier.identifier)
  }
  
  func registerNibForHeaderFooterView<T: NibResource where T: Reusable, T.T: UIView>(nibResource: T) {
    registerNib(nibResource.instance, forHeaderFooterViewReuseIdentifier: nibResource.reuseIdentifier.identifier)
  }
  
  func registerNibs<T: NibResource where T: Reusable, T.T: UITableViewCell>(nibResources: [T]) {
    nibResources.forEach(registerNib)
  }
}

extension UICollectionView {
  func dequeueReusableCellWithReuseIdentifier<T: UICollectionViewCell>(identifier: ReuseIdentifier<T>, forIndexPath indexPath: NSIndexPath) -> T? {
    return dequeueReusableCellWithReuseIdentifier(identifier.identifier, forIndexPath: indexPath) as? T
  }
  
  func dequeueReusableSupplementaryViewOfKind<T: UICollectionReusableView>(elementKind: String, withReuseIdentifier identifier: ReuseIdentifier<T>, forIndexPath indexPath: NSIndexPath) -> T? {
    return dequeueReusableSupplementaryViewOfKind(elementKind, withReuseIdentifier: identifier.identifier, forIndexPath: indexPath) as? T
  }
  
  func registerNib<T: NibResource where T: Reusable, T.T: UICollectionViewCell>(nibResource: T) {
    registerNib(nibResource.instance, forCellWithReuseIdentifier: nibResource.reuseIdentifier.identifier)
  }
  
  func registerNib<T: NibResource where T: Reusable, T.T: UICollectionReusableView>(nibResource: T, forSupplementaryViewOfKind kind: String) {
    registerNib(nibResource.instance, forSupplementaryViewOfKind: kind, withReuseIdentifier: nibResource.reuseIdentifier.identifier)
  }
  
  func registerNibs<T: NibResource where T: Reusable, T.T: UICollectionViewCell>(nibResources: [T]) {
    nibResources.forEach(registerNib)
  }
  
  func registerNibs<T: NibResource where T: Reusable, T.T: UICollectionReusableView>(nibResources: [T], forSupplementaryViewOfKind kind: String) {
    nibResources.forEach { self.registerNib($0, forSupplementaryViewOfKind: kind) }
  }
}

extension UIViewController {
  convenience init(nib: NibResource) {
    self.init(nibName: nib.name, bundle: nil)
  }
}